# Generated by Django 5.1.15 on 2026-09-05 17:43

import albums.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_drive_folder_id', models.CharField(max_length=255)),
                ('folder_name', models.CharField(max_length=255)),
                ('share_token', models.CharField(db_index=True, default=albums.models.generate_share_token, max_length=64, unique=True)),
                ('is_share_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=20)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('processed_images', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='albums.album')),
            ],
            options={
                'verbose_name': 'Job de Processamento',
                'verbose_name_plural': 'Jobs de Processamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='albums.album')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Álbum',
                'verbose_name_plural': 'Compartilhamentos de Álbuns',
                'unique_together': {('album', 'invited_email')},
            },
        ),
    ]
