# Generated by Django 5.1.15 on 2026-09-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumshare',
            options={'ordering': ['-invited_at'], 'verbose_name': 'Compartilhamento de Álbum', 'verbose_name_plural': 'Compartilhamentos de Álbuns'},
        ),
        migrations.AddField(
            model_name='albumshare',
            name='invite_type',
            field=models.CharField(choices=[('EMAIL', 'Convidado por e-mail'), ('LINK', 'Convidado por link')], db_index=True, default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='albumshare',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='albumshare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
