# Generated by DriveFace AI

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_albumshare_options_albumshare_invite_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clustering_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
