# Generated by Django 5.1.15 on 2026-09-05 17:43

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Pessoa')),
                ('centroid_embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('total_samples', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identidade',
                'verbose_name_plural': 'Identidades',
                'ordering': ['person_name'],
                'unique_together': {('user', 'person_name')},
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Pessoa Desconhecida', max_length=255)),
                ('avatar_crop_webp', models.TextField(blank=True, help_text='Miniatura 160x160 px em Base64 para exibição do avatar na interface.', verbose_name='Avatar WebP (Base64)')),
                ('face_count', models.PositiveIntegerField(default=0)),
                ('is_suggested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='albums.album')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='faces.identity')),
            ],
            options={
                'verbose_name': 'Cluster de Faces',
                'verbose_name_plural': 'Clusters de Faces',
                'ordering': ['-face_count'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_file_id', models.CharField(db_index=True, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('faces_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.album')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'unique_together': {('album', 'google_file_id')},
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('bbox_xmin', models.FloatField(verbose_name='BBox Xmin (normalizado 0-1)')),
                ('bbox_ymin', models.FloatField(verbose_name='BBox Ymin (normalizado 0-1)')),
                ('bbox_xmax', models.FloatField(verbose_name='BBox Xmax (normalizado 0-1)')),
                ('bbox_ymax', models.FloatField(verbose_name='BBox Ymax (normalizado 0-1)')),
                ('detection_confidence', models.FloatField(verbose_name='Confiança da Detecção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces', to='faces.cluster')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_faces', to='faces.photo')),
            ],
            options={
                'verbose_name': 'Face Detectada',
                'verbose_name_plural': 'Faces Detectadas',
            },
        ),
    ]
