# Generated by Django 5.1.15 on 2026-09-11 03:30

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centroid_embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('total_samples', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='faces.identity')),
            ],
            options={
                'verbose_name': 'Template Facial',
                'verbose_name_plural': 'Templates Faciais',
                'ordering': ['-total_samples', '-created_at'],
            },
        ),
    ]
