# Generated by Django 5.1.15 on 2026-09-05 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_access_token', models.TextField(verbose_name='Access Token Criptografado')),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token Criptografado')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Google',
                'verbose_name_plural': 'Tokens Google',
            },
        ),
    ]
